@startuml Port

' Uncomment the line below for "dark mode" styling
'!$AWS_DARK = true

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v19.0/dist
!include AWSPuml/AWSCommon.puml

[c]
component C {
  port p1
  component c1
}

c --> p1
p1 --> c1

@enduml